apiVersion: v1
kind: ReplicationController
metadata:
  name: wso2am-api-publisher
  labels:
    name: wso2am-api-publisher
spec:
  replicas: 1
  selector:
    name: wso2am-api-publisher
  template:
    metadata:
      labels:
        name: wso2am-api-publisher
    spec:
      containers:
      - name: wso2am-api-publisher
        image: dockerhub.private.wso2.com/dimuthud-wso2-am-api-publisher:1.10.0
        imagePullPolicy: Always
      imagePullSecrets:
      - name: registrypullsecret